// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/flame-f5.png --width 34 --eye-row -1
// Source: assets/flame-f5.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#100f0b0');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(15) + chalk.hex('#ffffff')('▄') + chalk.hex('#f3f2f2')('▄') + ' '.repeat(17),
    ' '.repeat(15) +
      chalk.hex('#866329')('▄') +
      chalk.bgHex('#f8ebb1').hex('#f9e171')('▄') +
      chalk.bgHex('#96741c').hex('#debf3e')('▄') +
      chalk.hex('#6c4107')('▄') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.hex('#d5b32c')('▄') +
      chalk.bgHex('#ebcf56').hex('#e3c648')('▄') +
      chalk.bgHex('#d9af34').hex('#f0d560')('▄') +
      chalk.bgHex('#e1c344').hex('#cfa923')('▄') +
      chalk.bgHex('#c8a315').hex('#c9a517')('▄') +
      chalk.bgHex('#dab252').hex('#be770c')('▄') +
      chalk.hex('#9e4704')('▄') +
      ' '.repeat(13),
    ' '.repeat(12) +
      chalk.hex('#ab6109')('▄') +
      chalk.bgHex('#c29311').hex('#c69612')('▄') +
      chalk.bgHex('#d8b834').hex('#d8b834')('▄') +
      chalk.bgHex('#edd35a').hex('#fbe375')('▄') +
      chalk.bgHex('#fde578').hex('#fce376')('▄') +
      chalk.bgHex('#d4b32c').hex('#edd25a')('▄') +
      chalk.bgHex('#c99412').hex('#c79512')('▄') +
      chalk.bgHex('#bf790d').hex('#c1720b')('▄') +
      chalk.bgHex('#b85b07').hex('#b85b07')('▄') +
      chalk.bgHex('#741d00').hex('#aa3400')('▄') +
      ' '.repeat(12),
    ' '.repeat(11) +
      chalk.bgHex('#892e01').hex('#b34202')('▄') +
      chalk.bgHex('#c06e0a').hex('#bf6c0a')('▄') +
      chalk.bgHex('#c69412').hex('#c58f10')('▄') +
      chalk.bgHex('#e7cb51').hex('#f8de6f')('▄') +
      chalk.bgHex('#fae173').hex('#fae37a')('▄') +
      chalk.bgHex('#fae173').hex('#fae379')('▄') +
      chalk.bgHex('#f8df70').hex('#f8de6f')('▄') +
      chalk.bgHex('#c9981a').hex('#d7ad40')('▄') +
      chalk.bgHex('#c1700a').hex('#bf6d0b')('▄') +
      chalk.bgHex('#b95706').hex('#b95505')('▄') +
      chalk.bgHex('#aa3400').hex('#a93400')('▄') +
      chalk.bgHex('#8b2100').hex('#8f2300')('▄') +
      ' '.repeat(11),
    ' '.repeat(10) +
      chalk.bgHex('#862200').hex('#962700')('▄') +
      chalk.bgHex('#b33e01').hex('#b03b01')('▄') +
      chalk.bgHex('#be6608').hex('#bc5c07')('▄') +
      chalk.bgHex('#c4860f').hex('#c27b0c')('▄') +
      chalk.bgHex('#f8de71').hex('#f7db71')('▄') +
      chalk.bgHex('#fbe786').hex('#fae685')('▄') +
      chalk.bgHex('#fbe786').hex('#ebd87c')('▄') +
      chalk.bgHex('#f7dc6d').hex('#f6da6d')('▄') +
      chalk.bgHex('#e4bf5a').hex('#f6db7b')('▄') +
      chalk.bgHex('#be6709').hex('#bc5d07')('▄') +
      chalk.bgHex('#b84f04').hex('#b64703')('▄') +
      chalk.bgHex('#a73200').hex('#a32f00')('▄') +
      chalk.bgHex('#8e2200').hex('#8c2000')('▄') +
      chalk.bgHex('#5c0c00').hex('#6a1000')('▄') +
      ' '.repeat(10),
    ' '.repeat(9) +
      chalk.hex('#671500')('▄') +
      chalk.bgHex('#922500').hex('#8d2100')('▄') +
      chalk.bgHex('#ab3701').hex('#962e00')('▄') +
      chalk.bgHex('#ba5104').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#1d0900').hex('#220c00')('▄') +
      chalk.bgHex('#210b00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#200a00').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#210c00')('▄') +
      chalk.bgHex('#5b2702').hex('#210c00')('▄') +
      chalk.bgHex('#b43d01').hex('#1a0800')('▄') +
      chalk.bgHex('#9d2c00').hex('#972800')('▄') +
      chalk.bgHex('#881e00').hex('#831b00')('▄') +
      chalk.bgHex('#681100').hex('#5b0c00')('▄') +
      ' '.repeat(10),
    ' '.repeat(10) +
      chalk.bgHex('#871d00').hex('#7a1a00')('▄') +
      chalk.bgHex('#0a0300').hex('#715a0b')('▄') +
      chalk.bgHex('#c39f14').hex('#ebddbc')('▄') +
      chalk.bgHex('#c5a115').hex('#c8a415')('▄') +
      chalk.bgHex('#0a0300').hex('#7e650d')('▄') +
      chalk.bgHex('#220c00').hex('#140700')('▄') +
      chalk.bgHex('#220c00').hex('#160800')('▄') +
      chalk.bgHex('#130b01').hex('#c8a416')('▄') +
      chalk.bgHex('#c8a415').hex('#b17d15')('▄') +
      chalk.bgHex('#83690d').hex('#c8a415')('▄') +
      chalk.bgHex('#0a0300').hex('#7e650d')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#7e1800').hex('#7a1500')('▄') +
      ' '.repeat(11),
    ' '.repeat(10) +
      chalk.bgHex('#300b00').hex('#250b00')('▄') +
      chalk.bgHex('#c8a415').hex('#0c0500')('▄') +
      chalk.bgHex('#7a1800').hex('#c39c14')('▄') +
      chalk.bgHex('#7b1b00').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#0f0700')('▄') +
      chalk.bgHex('#0b0300').hex('#200b00')('▄') +
      chalk.bgHex('#0c0400').hex('#210b00')('▄') +
      chalk.bgHex('#a15e0b').hex('#8b700e')('▄') +
      chalk.bgHex('#7a1800').hex('#bc8f12')('▄') +
      chalk.bgHex('#c7a215').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#0f0700')('▄') +
      chalk.bgHex('#1b0800').hex('#1a0800')('▄') +
      chalk.hex('#5a1100')('▀') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#100500').hex('#1a0800')('▄') +
      chalk.bgHex('#100500').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#210c00').hex('#220c00')('▄') +
      chalk.bgHex('#0e0500').hex('#220c00')('▄') +
      chalk.bgHex('#170800').hex('#210b00')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#210900')('▄') +
      ' '.repeat(12),
    ' '.repeat(12) +
      chalk.hex('#1a0800')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1e0a00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#3e1200')('▄') +
      chalk.hex('#1a0800')('▀') +
      ' '.repeat(13),
    ' '.repeat(14) +
      chalk.bgHex('#721500').hex('#7b1e00')('▄') +
      chalk.bgHex('#741400').hex('#721600')('▄') +
      chalk.bgHex('#751400').hex('#731600')('▄') +
      chalk.bgHex('#741500').hex('#6d1300')('▄') +
      chalk.hex('#6d1700')('▀') +
      ' '.repeat(15),
    ' '.repeat(10) +
      chalk.hex('#8b2200')('▄') +
      chalk.hex('#841e00')('▄') +
      chalk.hex('#ae760e')('▄') +
      chalk.hex('#832000')('▄') +
      chalk.hex('#841f00')('▄') +
      chalk.bgHex('#782100').hex('#841f00')('▄') +
      chalk.bgHex('#7b1b00').hex('#841f00')('▄') +
      chalk.hex('#832000')('▄') +
      chalk.hex('#831e00')('▄') +
      chalk.hex('#821e00')('▄') +
      chalk.hex('#b57e0e')('▄') +
      chalk.hex('#811d00')('▄') +
      ' '.repeat(12),
    ' '.repeat(9) +
      chalk.hex('#7e1c00')('▀') +
      chalk.bgHex('#821d00').hex('#832000')('▄') +
      chalk.bgHex('#821f00').hex('#7f1e00')('▄') +
      chalk.bgHex('#be9211').hex('#801d00')('▄') +
      chalk.bgHex('#841e00').hex('#811d00')('▄') +
      chalk.bgHex('#841e00').hex('#811d00')('▄') +
      chalk.bgHex('#831e00').hex('#811d00')('▄') +
      chalk.bgHex('#cd5f00').hex('#cc6000')('▄') +
      chalk.bgHex('#821e00').hex('#821d00')('▄') +
      chalk.bgHex('#831e00').hex('#801d00')('▄') +
      chalk.bgHex('#974806').hex('#7f1e00')('▄') +
      chalk.bgHex('#be9211').hex('#801e00')('▄') +
      chalk.bgHex('#811e00').hex('#7e1c00')('▄') +
      chalk.hex('#7f1c00')('▀') +
      chalk.hex('#891e00')('▀') +
      ' '.repeat(10),
    ' '.repeat(34),
  ];
}
