// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/flame-f3.png --width 34 --eye-row -1
// Source: assets/flame-f3.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#e0e0e0');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(17) + chalk.hex('#fcfafa')('▄') + chalk.hex('#ffffff')('▄') + ' '.repeat(15),
    ' '.repeat(16) +
      chalk.bgHex('#72460b').hex('#c9a518')('▄') +
      chalk.hex('#e6e2e0')('▀') +
      ' '.repeat(16),
    ' '.repeat(14) +
      chalk.hex('#d9b156')('▀') +
      chalk.bgHex('#bf7b0d').hex('#6f3e09')('▄') +
      chalk.hex('#c9830e')('▄') +
      chalk.bgHex('#c7840f').hex('#d4b22c')('▄') +
      chalk.hex('#f3d762')('▄') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.bgHex('#874004').hex('#bd6207')('▄') +
      chalk.bgHex('#c27e0e').hex('#c37e0d')('▄') +
      chalk.bgHex('#c9a017').hex('#c8a314')('▄') +
      chalk.bgHex('#e6c953').hex('#fae274')('▄') +
      chalk.bgHex('#fde67a').hex('#fae276')('▄') +
      chalk.bgHex('#dfc03f').hex('#e9ce55')('▄') +
      chalk.bgHex('#c8a516').hex('#ceab21')('▄') +
      chalk.hex('#c8850e')('▄') +
      ' '.repeat(12),
    ' '.repeat(12) +
      chalk.hex('#5d1100')('▄') +
      chalk.bgHex('#ac3600').hex('#ac3500')('▄') +
      chalk.bgHex('#bd6108').hex('#bd5f07')('▄') +
      chalk.bgHex('#c37c0d').hex('#c2790c')('▄') +
      chalk.bgHex('#c7a015').hex('#e9cd5d')('▄') +
      chalk.bgHex('#f9e172').hex('#f8e174')('▄') +
      chalk.bgHex('#fae274').hex('#f9e072')('▄') +
      chalk.bgHex('#fbe683').hex('#fae584')('▄') +
      chalk.bgHex('#c29d1b').hex('#d3ad2b')('▄') +
      chalk.bgHex('#c98a0f').hex('#b3740b')('▄') +
      chalk.bgHex('#c86607').hex('#c76506')('▄') +
      ' '.repeat(11),
    ' '.repeat(12) +
      chalk.bgHex('#8e2200').hex('#8b2000')('▄') +
      chalk.bgHex('#aa3400').hex('#a53000')('▄') +
      chalk.bgHex('#bc5906').hex('#ba5004')('▄') +
      chalk.bgHex('#c1710b').hex('#bf6709')('▄') +
      chalk.bgHex('#fae585').hex('#fae485')('▄') +
      chalk.bgHex('#fae482').hex('#f9e384')('▄') +
      chalk.bgHex('#f8de6f').hex('#eacf67')('▄') +
      chalk.bgHex('#f9e37e').hex('#f7dd72')('▄') +
      chalk.bgHex('#f7dc72').hex('#f7db72')('▄') +
      chalk.bgHex('#c1770c').hex('#c06d0a')('▄') +
      chalk.bgHex('#a94905').hex('#b74903')('▄') +
      chalk.hex('#8f2700')('▄') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.bgHex('#5c0d00').hex('#5b0d00')('▄') +
      chalk.bgHex('#881e00').hex('#831b00')('▄') +
      chalk.bgHex('#a02e00').hex('#711f00')('▄') +
      chalk.bgHex('#ad4103').hex('#1c0800')('▄') +
      chalk.bgHex('#1d0a00').hex('#220c00')('▄') +
      chalk.bgHex('#1b0900').hex('#220c00')('▄') +
      chalk.bgHex('#210c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#1f0a00').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#2b1101').hex('#210c00')('▄') +
      chalk.bgHex('#b34102').hex('#1a0800')('▄') +
      chalk.bgHex('#9b2b00').hex('#942600')('▄') +
      chalk.hex('#731400')('▄') +
      ' '.repeat(9),
    ' '.repeat(11) +
      chalk.hex('#550e00')('▀') +
      chalk.bgHex('#7e1700').hex('#520f00')('▄') +
      chalk.bgHex('#1a0800').hex('#120600')('▄') +
      chalk.bgHex('#191002').hex('#c8a415')('▄') +
      chalk.bgHex('#c5a115').hex('#d6bc52')('▄') +
      chalk.bgHex('#c39f14').hex('#b68410')('▄') +
      chalk.bgHex('#0a0300').hex('#70580b')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#170800').hex('#0a0300')('▄') +
      chalk.bgHex('#191002').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#f4ecd4')('▄') +
      chalk.bgHex('#7a620c').hex('#c8a415')('▄') +
      chalk.bgHex('#150600').hex('#0a0300')('▄') +
      chalk.bgHex('#731300').hex('#6b1200')('▄') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#0b0300').hex('#1f0a00')('▄') +
      chalk.bgHex('#c8a415').hex('#977b10')('▄') +
      chalk.bgHex('#7b1b00').hex('#c8a415')('▄') +
      chalk.bgHex('#7a1800').hex('#c39c14')('▄') +
      chalk.bgHex('#c8a415').hex('#0c0400')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#2c2004').hex('#0b0400')('▄') +
      chalk.bgHex('#c8a415').hex('#977b10')('▄') +
      chalk.bgHex('#7a1800').hex('#c7a315')('▄') +
      chalk.bgHex('#7a1800').hex('#c8a415')('▄') +
      chalk.bgHex('#1d1302').hex('#0c0400')('▄') +
      chalk.hex('#7d2300')('▀') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.hex('#3e1300')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#210b00').hex('#1b0800')('▄') +
      chalk.bgHex('#100500').hex('#220c00')('▄') +
      chalk.bgHex('#100500').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#210b00').hex('#220c00')('▄') +
      chalk.bgHex('#0d0500').hex('#220c00')('▄') +
      chalk.bgHex('#180800').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#3a1200')('▄') +
      ' '.repeat(10),
    ' '.repeat(13) +
      chalk.hex('#632100')('▀') +
      chalk.hex('#1a0800')('▀') +
      chalk.bgHex('#1a0800').hex('#1d0800')('▄') +
      chalk.bgHex('#220b00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#210b00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#260a00')('▄') +
      chalk.hex('#1a0800')('▀') +
      ' '.repeat(11),
    ' '.repeat(16) +
      chalk.hex('#6b1200')('▀') +
      chalk.bgHex('#751400').hex('#711500')('▄') +
      chalk.bgHex('#751400').hex('#731600')('▄') +
      chalk.bgHex('#741500').hex('#641300')('▄') +
      chalk.hex('#681200')('▀') +
      ' '.repeat(13),
    ' '.repeat(11) +
      chalk.hex('#822000')('▄') +
      chalk.hex('#7e1b00')('▄') +
      chalk.hex('#aa6d0c')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7f1c00')('▄') +
      chalk.bgHex('#691800').hex('#7e1c00')('▄') +
      chalk.bgHex('#7b1b00').hex('#801c00')('▄') +
      chalk.hex('#801c00')('▄') +
      chalk.hex('#801c00')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#9a4d07')('▄') +
      chalk.hex('#801d00')('▄') +
      chalk.hex('#801c00')('▄') +
      ' '.repeat(9),
    ' '.repeat(10) +
      chalk.hex('#7c1b00')('▀') +
      chalk.bgHex('#7c1a00').hex('#7c1a00')('▄') +
      chalk.bgHex('#7d1b00').hex('#7d1a00')('▄') +
      chalk.bgHex('#bb8d11').hex('#7b1a00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7e1b00')('▄') +
      chalk.bgHex('#7e1c00').hex('#7d1b00')('▄') +
      chalk.bgHex('#7e1c00').hex('#7d1b00')('▄') +
      chalk.bgHex('#ba4f00').hex('#ba5000')('▄') +
      chalk.bgHex('#7f1c00').hex('#7e1b00')('▄') +
      chalk.bgHex('#7e1c00').hex('#7e1b00')('▄') +
      chalk.bgHex('#7e1c00').hex('#7d1b00')('▄') +
      chalk.bgHex('#bc8b11').hex('#7e1b00')('▄') +
      chalk.bgHex('#924106').hex('#7c1b00')('▄') +
      chalk.bgHex('#7d1b00').hex('#7d1b00')('▄') +
      chalk.hex('#7d1b00')('▀') +
      chalk.hex('#7c1d00')('▀') +
      ' '.repeat(7),
    ' '.repeat(34),
  ];
}
