// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/flame-f2.png --width 34 --eye-row -1
// Source: assets/flame-f2.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#b09020');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(17) + chalk.hex('#ffffff')('▄') + chalk.hex('#ffffff')('▄') + ' '.repeat(15),
    ' '.repeat(16) +
      chalk.hex('#a26c0c')('▄') +
      chalk.bgHex('#b7941e').hex('#957220')('▄') +
      chalk.hex('#ffffff')('▀') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.hex('#ffe77b')('▀') +
      chalk.hex('#d7aa4c')('▀') +
      chalk.bgHex('#bb8e11').hex('#875c0a')('▄') +
      chalk.hex('#c79b12')('▄') +
      chalk.bgHex('#c99111').hex('#ecd058')('▄') +
      chalk.hex('#e7ca4e')('▄') +
      ' '.repeat(14),
    ' '.repeat(14) +
      chalk.hex('#b34c04')('▄') +
      chalk.bgHex('#ad6109').hex('#be6a09')('▄') +
      chalk.bgHex('#c78f11').hex('#c69010')('▄') +
      chalk.bgHex('#cdab27').hex('#e6ca4e')('▄') +
      chalk.bgHex('#fde579').hex('#fbe376')('▄') +
      chalk.bgHex('#f2d764').hex('#fbe377')('▄') +
      chalk.bgHex('#ddbe3d').hex('#dec03e')('▄') +
      chalk.hex('#c79f13')('▄') +
      ' '.repeat(12),
    ' '.repeat(13) +
      chalk.bgHex('#912800').hex('#a02d00')('▄') +
      chalk.bgHex('#b74c04').hex('#b74a03')('▄') +
      chalk.bgHex('#be6809').hex('#be6508')('▄') +
      chalk.bgHex('#c58e10').hex('#c48910')('▄') +
      chalk.bgHex('#f8df6f').hex('#fae786')('▄') +
      chalk.bgHex('#fae173').hex('#f9e071')('▄') +
      chalk.bgHex('#fbe378').hex('#f9e071')('▄') +
      chalk.bgHex('#f2db71').hex('#fae584')('▄') +
      chalk.bgHex('#bf9611').hex('#c59312')('▄') +
      chalk.bgHex('#c97f0d').hex('#b8710b')('▄') +
      ' '.repeat(11),
    ' '.repeat(12) +
      chalk.bgHex('#7d1900').hex('#811900')('▄') +
      chalk.bgHex('#9d2c00').hex('#9a2900')('▄') +
      chalk.bgHex('#b64503').hex('#b43e01')('▄') +
      chalk.bgHex('#bc6007').hex('#bb5606')('▄') +
      chalk.bgHex('#d6a438').hex('#ecc55f')('▄') +
      chalk.bgHex('#fae685').hex('#a79353')('▄') +
      chalk.bgHex('#f8de6f').hex('#634e24')('▄') +
      chalk.bgHex('#f8de6f').hex('#846d34')('▄') +
      chalk.bgHex('#fae483').hex('#d5bd66')('▄') +
      chalk.bgHex('#c48910').hex('#c27d0d')('▄') +
      chalk.bgHex('#bf6b0a').hex('#bd6108')('▄') +
      chalk.bgHex('#9b3b03').hex('#b33f01')('▄') +
      chalk.hex('#6b1900')('▄') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.bgHex('#7e1700').hex('#781400')('▄') +
      chalk.bgHex('#952600').hex('#8d2200')('▄') +
      chalk.bgHex('#ae3901').hex('#1a0800')('▄') +
      chalk.bgHex('#200b00').hex('#210b00')('▄') +
      chalk.bgHex('#1c0900').hex('#120600')('▄') +
      chalk.bgHex('#220c00').hex('#200b00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#190900')('▄') +
      chalk.bgHex('#743303').hex('#120600')('▄') +
      chalk.bgHex('#ad3a01').hex('#441500')('▄') +
      chalk.bgHex('#932500').hex('#8e2200')('▄') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.bgHex('#751300').hex('#721400')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#0a0300').hex('#3b2c05')('▄') +
      chalk.bgHex('#a58711').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#f2e9e2')('▄') +
      chalk.bgHex('#b69513').hex('#b1790f')('▄') +
      chalk.bgHex('#170800').hex('#0a0300')('▄') +
      chalk.bgHex('#220c00').hex('#1e0a00')('▄') +
      chalk.bgHex('#0a0300').hex('#3b2c05')('▄') +
      chalk.bgHex('#c8a415').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#bf9080')('▄') +
      chalk.bgHex('#2f2204').hex('#c8a415')('▄') +
      chalk.bgHex('#881e00').hex('#3d0e00')('▄') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.hex('#5c0f00')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#5e4a09').hex('#0d0400')('▄') +
      chalk.bgHex('#c8a415').hex('#5e4a09')('▄') +
      chalk.bgHex('#7a1800').hex('#c8a415')('▄') +
      chalk.bgHex('#7a1800').hex('#775f0c')('▄') +
      chalk.bgHex('#0a0300').hex('#1d0b00')('▄') +
      chalk.bgHex('#1c0a00').hex('#220c00')('▄') +
      chalk.bgHex('#5e4a09').hex('#0d0400')('▄') +
      chalk.bgHex('#c7a315').hex('#bf9c14')('▄') +
      chalk.bgHex('#7a1800').hex('#c8a415')('▄') +
      chalk.bgHex('#aa700d').hex('#0f0700')('▄') +
      chalk.bgHex('#160600').hex('#210900')('▄') +
      ' '.repeat(9),
    ' '.repeat(13) +
      chalk.bgHex('#1a0800').hex('#541c00')('▄') +
      chalk.bgHex('#210b00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1b0800')('▄') +
      chalk.bgHex('#1c0a00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#1d0b00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      ' '.repeat(10),
    ' '.repeat(14) +
      chalk.hex('#1a0800')('▀') +
      chalk.hex('#1a0800')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#210b00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1f0a00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#2d0a00')('▄') +
      chalk.hex('#1a0800')('▀') +
      ' '.repeat(11),
    ' '.repeat(16) +
      chalk.hex('#8f2b00')('▀') +
      chalk.bgHex('#721600').hex('#601500')('▄') +
      chalk.bgHex('#731400').hex('#731700')('▄') +
      chalk.bgHex('#741400').hex('#721700')('▄') +
      chalk.bgHex('#711500').hex('#8e2b00')('▄') +
      ' '.repeat(13),
    ' '.repeat(9) +
      chalk.hex('#7f1c00')('▄') +
      chalk.hex('#7b1b00')('▄') +
      chalk.hex('#7c1b00')('▄') +
      chalk.hex('#872b02')('▄') +
      chalk.hex('#ba8c10')('▄') +
      chalk.hex('#7d1c00')('▄') +
      chalk.bgHex('#9e2c00').hex('#7d1c00')('▄') +
      chalk.bgHex('#8f2500').hex('#7e1b00')('▄') +
      chalk.bgHex('#8e2400').hex('#7e1d00')('▄') +
      chalk.bgHex('#731900').hex('#7e1d00')('▄') +
      chalk.bgHex('#8a2200').hex('#7e1d00')('▄') +
      chalk.bgHex('#922600').hex('#7e1d00')('▄') +
      chalk.bgHex('#962600').hex('#7e1d00')('▄') +
      chalk.bgHex('#a32d00').hex('#7e1d00')('▄') +
      chalk.hex('#903e04')('▄') +
      chalk.hex('#bb8b11')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7d1c00')('▄') +
      chalk.hex('#7c1b00')('▄') +
      ' '.repeat(6),
    ' '.repeat(9) +
      chalk.hex('#7a1a00')('▀') +
      chalk.hex('#7c1b00')('▀') +
      chalk.hex('#7c1b00')('▀') +
      chalk.bgHex('#7c1b00').hex('#7f1d00')('▄') +
      chalk.bgHex('#9f5809').hex('#7a1d00')('▄') +
      chalk.bgHex('#7c1c00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7e1c00').hex('#7c1a00')('▄') +
      chalk.bgHex('#7d1c00').hex('#7d1c00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7c1c00')('▄') +
      chalk.bgHex('#d66800').hex('#7e1c00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7e1c00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7e1c00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7e1c00')('▄') +
      chalk.bgHex('#7e1c00').hex('#7c1c00')('▄') +
      chalk.bgHex('#7d1c00').hex('#7e1b00')('▄') +
      chalk.bgHex('#994c07').hex('#811c00')('▄') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7c1a00')('▀') +
      chalk.hex('#7b1b00')('▀') +
      chalk.hex('#7a1800')('▀') +
      ' '.repeat(5),
    ' '.repeat(34),
  ];
}
