// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/flame-f7.png --width 34 --eye-row -1
// Source: assets/flame-f7.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#d0c090');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(16) + chalk.hex('#ffffff')('▄') + chalk.hex('#ffffff')('▄') + ' '.repeat(16),
    ' '.repeat(16) +
      chalk.bgHex('#cebd90').hex('#f3db70')('▄') +
      chalk.bgHex('#e0c55a').hex('#e7cb50')('▄') +
      chalk.hex('#bd9814')('▄') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.hex('#b39124')('▄') +
      chalk.bgHex('#ae8d34').hex('#ddbe3c')('▄') +
      chalk.bgHex('#dfba3f').hex('#f3da65')('▄') +
      chalk.bgHex('#e4c248').hex('#d0ad24')('▄') +
      chalk.bgHex('#cfad23').hex('#d0ab23')('▄') +
      chalk.bgHex('#dcac3e').hex('#c1840f')('▄') +
      chalk.bgHex('#ddbb5f').hex('#b96308')('▄') +
      ' '.repeat(13),
    ' '.repeat(13) +
      chalk.bgHex('#89590a').hex('#c69011')('▄') +
      chalk.bgHex('#d3b12a').hex('#d4b32c')('▄') +
      chalk.bgHex('#e7cc4f').hex('#fbe274')('▄') +
      chalk.bgHex('#fde579').hex('#fce476')('▄') +
      chalk.bgHex('#d9ba36').hex('#efd55d')('▄') +
      chalk.bgHex('#ca9916').hex('#c89b13')('▄') +
      chalk.bgHex('#c1840f').hex('#c27b0d')('▄') +
      chalk.bgHex('#ba6709').hex('#bb6609')('▄') +
      chalk.bgHex('#ad3600').hex('#b03a00')('▄') +
      chalk.hex('#7e1d00')('▄') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.hex('#a23400')('▄') +
      chalk.bgHex('#be6709').hex('#be6608')('▄') +
      chalk.bgHex('#c58e11').hex('#c58a10')('▄') +
      chalk.bgHex('#e6c94e').hex('#f8de6f')('▄') +
      chalk.bgHex('#fae172').hex('#fbe787')('▄') +
      chalk.bgHex('#fae273').hex('#f9e072')('▄') +
      chalk.bgHex('#fae277').hex('#f8df6f')('▄') +
      chalk.bgHex('#c79812').hex('#cfa229')('▄') +
      chalk.bgHex('#c1760c').hex('#c1740b')('▄') +
      chalk.bgHex('#bb6008').hex('#bb5d07')('▄') +
      chalk.bgHex('#b03900').hex('#af3800')('▄') +
      chalk.bgHex('#952600').hex('#952600')('▄') +
      chalk.hex('#5c0d00')('▄') +
      ' '.repeat(10),
    ' '.repeat(10) +
      chalk.bgHex('#6a1600').hex('#922500')('▄') +
      chalk.bgHex('#b13a01').hex('#ae3801')('▄') +
      chalk.bgHex('#bd6008').hex('#bb5807')('▄') +
      chalk.bgHex('#c3820e').hex('#c1760c')('▄') +
      chalk.bgHex('#fae583').hex('#f9e381')('▄') +
      chalk.bgHex('#fbe786').hex('#fae585')('▄') +
      chalk.bgHex('#f9e075').hex('#e9d16d')('▄') +
      chalk.bgHex('#f7dd6d').hex('#f6db6d')('▄') +
      chalk.bgHex('#e4be56').hex('#f5dc7a')('▄') +
      chalk.bgHex('#c16c0a').hex('#be6308')('▄') +
      chalk.bgHex('#ba5605').hex('#b84e03')('▄') +
      chalk.bgHex('#ac3500').hex('#a73200')('▄') +
      chalk.bgHex('#932500').hex('#902400')('▄') +
      chalk.bgHex('#741300').hex('#761400')('▄') +
      ' '.repeat(10),
    ' '.repeat(10) +
      chalk.bgHex('#8f2300').hex('#8a2000')('▄') +
      chalk.bgHex('#a83400').hex('#942c00')('▄') +
      chalk.bgHex('#b94d04').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#1d0900').hex('#220c00')('▄') +
      chalk.bgHex('#210b00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#200a00').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#210c00')('▄') +
      chalk.bgHex('#5c2902').hex('#210c00')('▄') +
      chalk.bgHex('#b54302').hex('#1a0800')('▄') +
      chalk.bgHex('#a22f00').hex('#9b2b00')('▄') +
      chalk.bgHex('#8d2100').hex('#881e00')('▄') +
      chalk.bgHex('#721300').hex('#640e00')('▄') +
      ' '.repeat(10),
    ' '.repeat(10) +
      chalk.bgHex('#851c00').hex('#781800')('▄') +
      chalk.bgHex('#0a0300').hex('#715a0b')('▄') +
      chalk.bgHex('#c39f14').hex('#ebddbc')('▄') +
      chalk.bgHex('#c5a115').hex('#c8a415')('▄') +
      chalk.bgHex('#0a0300').hex('#7e650d')('▄') +
      chalk.bgHex('#220c00').hex('#140700')('▄') +
      chalk.bgHex('#220c00').hex('#160800')('▄') +
      chalk.bgHex('#130b01').hex('#c8a416')('▄') +
      chalk.bgHex('#c8a415').hex('#b17d15')('▄') +
      chalk.bgHex('#83690d').hex('#c8a415')('▄') +
      chalk.bgHex('#0a0300').hex('#7e650d')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#821a00').hex('#7e1700')('▄') +
      ' '.repeat(11),
    ' '.repeat(10) +
      chalk.bgHex('#2f0b00').hex('#250b00')('▄') +
      chalk.bgHex('#c8a415').hex('#0c0500')('▄') +
      chalk.bgHex('#7a1800').hex('#c39c14')('▄') +
      chalk.bgHex('#7b1b00').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#0f0700')('▄') +
      chalk.bgHex('#0b0300').hex('#200b00')('▄') +
      chalk.bgHex('#0c0400').hex('#210b00')('▄') +
      chalk.bgHex('#a15e0b').hex('#8b700e')('▄') +
      chalk.bgHex('#7a1800').hex('#bc8f12')('▄') +
      chalk.bgHex('#c7a215').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#0f0700')('▄') +
      chalk.bgHex('#1b0800').hex('#1a0800')('▄') +
      chalk.hex('#5c1100')('▀') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#100500').hex('#1a0800')('▄') +
      chalk.bgHex('#100500').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#210c00').hex('#220c00')('▄') +
      chalk.bgHex('#0e0500').hex('#220c00')('▄') +
      chalk.bgHex('#170800').hex('#210b00')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#210900')('▄') +
      ' '.repeat(12),
    ' '.repeat(12) +
      chalk.hex('#1a0800')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1e0a00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#3e1200')('▄') +
      chalk.hex('#1a0800')('▀') +
      ' '.repeat(13),
    ' '.repeat(14) +
      chalk.bgHex('#741400').hex('#7b1e00')('▄') +
      chalk.bgHex('#751500').hex('#731500')('▄') +
      chalk.bgHex('#751400').hex('#731600')('▄') +
      chalk.bgHex('#741300').hex('#6c1300')('▄') +
      chalk.hex('#6c1900')('▀') +
      ' '.repeat(15),
    ' '.repeat(8) +
      chalk.hex('#7e1b00')('▄') +
      chalk.hex('#7f1d00')('▄') +
      chalk.hex('#a96a0b')('▄') +
      chalk.hex('#811c00')('▄') +
      chalk.hex('#811e00')('▄') +
      chalk.hex('#811e00')('▄') +
      chalk.hex('#811d00')('▄') +
      chalk.bgHex('#782100').hex('#811d00')('▄') +
      chalk.bgHex('#7b1b00').hex('#811d00')('▄') +
      chalk.hex('#811e00')('▄') +
      chalk.hex('#801c00')('▄') +
      chalk.hex('#801c00')('▄') +
      chalk.hex('#811d00')('▄') +
      chalk.hex('#872d03')('▄') +
      chalk.hex('#8e3804')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7f1e00')('▄') +
      ' '.repeat(9),
    ' '.repeat(6) +
      chalk.hex('#7a1a00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.bgHex('#7d1c00').hex('#7a1b00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7d1c00')('▄') +
      chalk.bgHex('#bd9011').hex('#7d1c00')('▄') +
      chalk.bgHex('#801e00').hex('#7e1b00')('▄') +
      chalk.bgHex('#801c00').hex('#7f1d00')('▄') +
      chalk.bgHex('#811c00').hex('#7e1d00')('▄') +
      chalk.bgHex('#811c00').hex('#801d00')('▄') +
      chalk.bgHex('#811c00').hex('#801d00')('▄') +
      chalk.bgHex('#c75b00').hex('#c85c00')('▄') +
      chalk.bgHex('#801c00').hex('#7f1d00')('▄') +
      chalk.bgHex('#811d00').hex('#7f1d00')('▄') +
      chalk.bgHex('#7f1d00').hex('#7e1b00')('▄') +
      chalk.bgHex('#801d00').hex('#7d1c00')('▄') +
      chalk.bgHex('#a86b0b').hex('#7d1c00')('▄') +
      chalk.bgHex('#b27d0e').hex('#7c1b00')('▄') +
      chalk.bgHex('#7d1a00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7c1b00').hex('#7b1b00')('▄') +
      chalk.hex('#7b1a00')('▀') +
      chalk.hex('#7a1b00')('▀') +
      ' '.repeat(7),
    ' '.repeat(34),
  ];
}
