// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/flame-f6.png --width 34 --eye-row -1
// Source: assets/flame-f6.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#f0e0b0');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(15) + chalk.hex('#ffffff')('▄') + chalk.hex('#f5f3f3')('▄') + ' '.repeat(17),
    ' '.repeat(15) +
      chalk.hex('#9a7a3b')('▄') +
      chalk.bgHex('#f4e6a9').hex('#f2d763')('▄') +
      chalk.bgHex('#926e10').hex('#d5b42d')('▄') +
      chalk.hex('#6c3c07')('▄') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.bgHex('#99772b').hex('#debf3c')('▄') +
      chalk.bgHex('#f0d55f').hex('#edd35b')('▄') +
      chalk.bgHex('#dbad35').hex('#dcbd3b')('▄') +
      chalk.bgHex('#daba36').hex('#d0a120')('▄') +
      chalk.bgHex('#c49412').hex('#c69913')('▄') +
      chalk.bgHex('#d7ad50').hex('#bb6a0a')('▄') +
      chalk.hex('#9e3d03')('▄') +
      ' '.repeat(13),
    ' '.repeat(12) +
      chalk.hex('#c3830e')('▄') +
      chalk.bgHex('#c8a617').hex('#cba81d')('▄') +
      chalk.bgHex('#e5c94d').hex('#efd45c')('▄') +
      chalk.bgHex('#fde578').hex('#fce476')('▄') +
      chalk.bgHex('#fae273').hex('#fbe274')('▄') +
      chalk.bgHex('#cba71b').hex('#cca91d')('▄') +
      chalk.bgHex('#c68a0f').hex('#c58a0f')('▄') +
      chalk.bgHex('#bc6d0a').hex('#bd6809')('▄') +
      chalk.bgHex('#b54f04').hex('#b55005')('▄') +
      chalk.bgHex('#761f00').hex('#a33000')('▄') +
      ' '.repeat(12),
    ' '.repeat(10) +
      chalk.hex('#732000')('▄') +
      chalk.bgHex('#b75a07').hex('#bb5a07')('▄') +
      chalk.bgHex('#c4830e').hex('#c27f0d')('▄') +
      chalk.bgHex('#caa319').hex('#c9a11b')('▄') +
      chalk.bgHex('#f9e172').hex('#fae582')('▄') +
      chalk.bgHex('#fae173').hex('#f9e071')('▄') +
      chalk.bgHex('#f9e275').hex('#f8e070')('▄') +
      chalk.bgHex('#eace57').hex('#f9e27a')('▄') +
      chalk.bgHex('#c5860f').hex('#c4820e')('▄') +
      chalk.bgHex('#bd6509').hex('#bd6208')('▄') +
      chalk.bgHex('#b54c04').hex('#b64a03')('▄') +
      chalk.bgHex('#a43000').hex('#a33000')('▄') +
      chalk.bgHex('#861d00').hex('#881e00')('▄') +
      ' '.repeat(11),
    ' '.repeat(9) +
      chalk.hex('#7d1c00')('▄') +
      chalk.bgHex('#aa3400').hex('#a73100')('▄') +
      chalk.bgHex('#b95506').hex('#b84d03')('▄') +
      chalk.bgHex('#c2780c').hex('#bf6c0a')('▄') +
      chalk.bgHex('#e3c35a').hex('#f2d776')('▄') +
      chalk.bgHex('#fae686').hex('#a79353')('▄') +
      chalk.bgHex('#f8de6f').hex('#6b5528')('▄') +
      chalk.bgHex('#f7dd6e').hex('#6b5528')('▄') +
      chalk.bgHex('#f9e382').hex('#d6bf6d')('▄') +
      chalk.bgHex('#c27a0d').hex('#c06f0b')('▄') +
      chalk.bgHex('#bb5b06').hex('#b95105')('▄') +
      chalk.bgHex('#b44302').hex('#b23b00')('▄') +
      chalk.bgHex('#a02e00').hex('#9c2b00')('▄') +
      chalk.bgHex('#881e00').hex('#851c00')('▄') +
      chalk.bgHex('#560d00').hex('#600e00')('▄') +
      ' '.repeat(10),
    ' '.repeat(9) +
      chalk.bgHex('#8a2000').hex('#861c00')('▄') +
      chalk.bgHex('#a12d00').hex('#992900')('▄') +
      chalk.bgHex('#b64202').hex('#190700')('▄') +
      chalk.bgHex('#200c00').hex('#120600')('▄') +
      chalk.bgHex('#1c0900').hex('#210b00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#180800')('▄') +
      chalk.bgHex('#1a0800').hex('#140700')('▄') +
      chalk.bgHex('#722b02').hex('#1e0a00')('▄') +
      chalk.bgHex('#ad3600').hex('#1a0800')('▄') +
      chalk.bgHex('#972800').hex('#912400')('▄') +
      chalk.bgHex('#821a00').hex('#7e1700')('▄') +
      chalk.bgHex('#5b0e00').hex('#500d00')('▄') +
      ' '.repeat(10),
    ' '.repeat(9) +
      chalk.bgHex('#7f1900').hex('#6f1300')('▄') +
      chalk.bgHex('#280a00').hex('#0a0300')('▄') +
      chalk.bgHex('#b79513').hex('#f4ecdc')('▄') +
      chalk.bgHex('#c8a415').hex('#944707')('▄') +
      chalk.bgHex('#a48611').hex('#c8a415')('▄') +
      chalk.bgHex('#1c0a00').hex('#0a0300')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#0a0300').hex('#614d0a')('▄') +
      chalk.bgHex('#c8a415').hex('#f1e7e1')('▄') +
      chalk.bgHex('#c8a415').hex('#c29813')('▄') +
      chalk.bgHex('#1b1202').hex('#c8a415')('▄') +
      chalk.bgHex('#1b0a00').hex('#0a0300')('▄') +
      chalk.bgHex('#401000').hex('#1a0800')('▄') +
      chalk.bgHex('#781400').hex('#6d1200')('▄') +
      ' '.repeat(11),
    ' '.repeat(10) +
      chalk.bgHex('#0a0300').hex('#170700')('▄') +
      chalk.bgHex('#7a1800').hex('#79610c')('▄') +
      chalk.bgHex('#7a1800').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#5d4909')('▄') +
      chalk.bgHex('#0a0300').hex('#200b00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#83690d').hex('#0b0300')('▄') +
      chalk.bgHex('#7a1800').hex('#c6a215')('▄') +
      chalk.bgHex('#7f2201').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#0a0300')('▄') +
      chalk.bgHex('#0a0300').hex('#200b00')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      ' '.repeat(12),
    ' '.repeat(10) +
      chalk.hex('#1d0800')('▀') +
      chalk.bgHex('#1a0900').hex('#1a0800')('▄') +
      chalk.bgHex('#1c0a00').hex('#1b0800')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#210c00').hex('#220c00')('▄') +
      chalk.bgHex('#1e0b00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1b0900').hex('#1a0800')('▄') +
      chalk.hex('#1c0800')('▀') +
      ' '.repeat(12),
    ' '.repeat(11) +
      chalk.hex('#441600')('▀') +
      chalk.hex('#1a0800')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#210b00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#1f0a00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#2b0a00')('▄') +
      chalk.hex('#1a0800')('▀') +
      chalk.hex('#3d1300')('▀') +
      ' '.repeat(13),
    ' '.repeat(13) +
      chalk.hex('#982b00')('▀') +
      chalk.bgHex('#741600').hex('#631600')('▄') +
      chalk.bgHex('#731400').hex('#741700')('▄') +
      chalk.bgHex('#731400').hex('#731700')('▄') +
      chalk.bgHex('#701500').hex('#8c2900')('▄') +
      ' '.repeat(16),
    ' '.repeat(7) +
      chalk.hex('#831c00')('▄') +
      chalk.hex('#801d00')('▄') +
      chalk.hex('#811e00')('▄') +
      chalk.hex('#b47d0e')('▄') +
      chalk.hex('#ad720c')('▄') +
      chalk.hex('#831f00')('▄') +
      chalk.bgHex('#9a2900').hex('#831f00')('▄') +
      chalk.bgHex('#972a00').hex('#831f00')('▄') +
      chalk.bgHex('#731a00').hex('#831f00')('▄') +
      chalk.bgHex('#731a00').hex('#831f00')('▄') +
      chalk.bgHex('#992700').hex('#832000')('▄') +
      chalk.bgHex('#a12900').hex('#831e00')('▄') +
      chalk.hex('#801e00')('▄') +
      chalk.hex('#ae750d')('▄') +
      chalk.hex('#b47e0f')('▄') +
      chalk.hex('#7e1e00')('▄') +
      chalk.hex('#7e1c00')('▄') +
      ' '.repeat(10),
    ' '.repeat(7) +
      chalk.hex('#7e1c00')('▀') +
      chalk.hex('#7e1d00')('▀') +
      chalk.hex('#7f1d00')('▀') +
      chalk.bgHex('#8f3803').hex('#882100')('▄') +
      chalk.bgHex('#8b2f03').hex('#821c00')('▄') +
      chalk.bgHex('#811e00').hex('#811d00')('▄') +
      chalk.bgHex('#831e00').hex('#801d00')('▄') +
      chalk.bgHex('#821e00').hex('#801d00')('▄') +
      chalk.bgHex('#c95c00').hex('#801d00')('▄') +
      chalk.bgHex('#c95d00').hex('#801d00')('▄') +
      chalk.bgHex('#821e00').hex('#7f1d00')('▄') +
      chalk.bgHex('#811e00').hex('#801d00')('▄') +
      chalk.bgHex('#801d00').hex('#7f1e00')('▄') +
      chalk.bgHex('#8b3003').hex('#7f1b00')('▄') +
      chalk.bgHex('#8d3803').hex('#821d00')('▄') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7c1d00')('▀') +
      chalk.hex('#7d1b00')('▀') +
      ' '.repeat(9),
    ' '.repeat(34),
  ];
}
