import type { ProjectType } from '../types.js';

// ─── Renderer ─────────────────────────────────────────────────────────────────

export function render(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => vars[key] ?? `{{${key}}}`);
}

// ─── AGENTS.md ────────────────────────────────────────────────────────────────

export function agentsMd(name: string, type: ProjectType, stack: string): string {
  return render(AGENTS_MD_TEMPLATE, { name, type, stack });
}

const AGENTS_MD_TEMPLATE = `# AGENTS — {{name}}

> lunatar multi-agent pipeline configuration.
> \`lunatar run "<intent>"\` — primary development workflow.

## Roles & models

| Role    | Default model        | Responsibility                               |
|---------|----------------------|----------------------------------------------|
| PO      | Llama 3.3 70B (Groq) | Clarify goal, extract requirements           |
| Planner | Gemini 2.5 Flash     | Architecture, tech breakdown, task list      |
| Dev     | Claude Sonnet 4.6    | Generate production-ready code               |
| QA      | Llama 3.3 70B (Groq) | Audit output, verdict PASS/FAIL, score 0–100 |

Override per run: press \`m\` in the TUI pipeline screen.

## Project

- **Name**: {{name}}
- **Type**: {{type}}
- **Stack**: {{stack}}

## Agent contracts

### PO
- Output JSON: \`{ clarifiedGoal, requirements[], constraints[], acceptanceCriteria[], complexity, assumptions[] }\`
- ≤ 12 requirements, each a clear testable statement — no implementation detail

### Planner
- Output JSON: \`{ architecture, techStack, tasks[], risks[] }\`
- Each task: \`{ id, description, files[], dependsOn[] }\`

### Dev
- Complete, runnable files — no \`// TODO\` placeholders
- Follow the stack: {{stack}}
- Must pass \`npm run lint\` and \`npm run typecheck\`
- TypeScript strict — no \`any\`, use \`unknown\` + type guards

### QA
- Output JSON: \`{ verdict: "PASS"|"FAIL", score: 0–100, issues[], suggestions[] }\`
- Issue: \`{ requirementId, description, severity: "low"|"medium"|"high" }\`

## Conventions

- \`import type\` for type-only imports
- Source in \`src/\`, tests in \`tests/\` (mirrors \`src/\`)
- Conventional Commits: \`feat:\` \`fix:\` \`refactor:\` \`test:\` \`chore:\`
- Vitest — ≥ 80% coverage on critical modules
`;

// ─── CLAUDE.md ────────────────────────────────────────────────────────────────

export function claudeMd(name: string, type: ProjectType, stack: string): string {
  return render(CLAUDE_MD_TEMPLATE, { name, type, stack });
}

const CLAUDE_MD_TEMPLATE = `# CLAUDE.md — {{name}}

> Claude Code intervention contract.
> Primary workflow: \`lunatar run "<intent>"\` — use Claude Code only for what the pipeline cannot handle.

## When to use Claude Code

- Multi-file architectural refactoring
- Complex debugging requiring cross-file tracing
- Security review
- Unblocking a failed pipeline step

## Project

- **Name**: {{name}} · **Type**: {{type}}
- **Stack**: {{stack}}
- **Source**: \`src/\` · **Tests**: \`tests/\` (mirrors \`src/\`)

## Rules

- TypeScript strict — no \`any\`, use \`unknown\` + type guards
- \`import type\` for type-only imports
- Conventional Commits: \`feat:\` \`fix:\` \`refactor:\` \`test:\` \`chore:\`
- No \`console.log\` in committed source code
- Do not modify \`dist/\` — generated by the build
- Run \`npm run typecheck && npm run lint && npm test\` before committing
`;

// ─── CI workflow ──────────────────────────────────────────────────────────────

export function ciYml(): string {
  return CI_YML;
}

const CI_YML = `name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: Lint · Types · Tests · Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
`;

// ─── .gitignore ───────────────────────────────────────────────────────────────

export function gitignore(): string {
  return GITIGNORE;
}

const GITIGNORE = `node_modules/
dist/
.env
.env.local
.env.*.local
logs/
*.log
coverage/
*.tsbuildinfo
.DS_Store
Thumbs.db
.vscode/
.idea/
*.swp
runs/
`;

// ─── .env.example ─────────────────────────────────────────────────────────────

export function envExample(): string {
  return ENV_EXAMPLE;
}

const ENV_EXAMPLE = `# lunatar LLM providers — fill in at least one

GROQ_API_KEY=
GEMINI_API_KEY=
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
NIM_API_KEY=
`;

// ─── eslint.config.js ─────────────────────────────────────────────────────────

export function eslintConfig(): string {
  return ESLINT_CONFIG;
}

const ESLINT_CONFIG = `import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';

export default tseslint.config(
  ...tseslint.configs.strictTypeChecked,
  eslintConfigPrettier,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ['tests/*.ts', 'tests/*/*.ts', 'tests/*/*/*.ts'],
          defaultProject: './tsconfig.test.json',
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-import-type-side-effects': 'error',
    },
  },
  {
    ignores: ['dist/**', 'node_modules/**', 'coverage/**', 'eslint.config.js', 'commitlint.config.cjs', 'vitest.config.ts', 'tsup.config.ts', 'vite.config.ts'],
  },
);
`;

// ─── .prettierrc ──────────────────────────────────────────────────────────────

export function prettierRc(): string {
  return PRETTIER_RC;
}

const PRETTIER_RC = `{
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 100,
  "tabWidth": 2
}
`;

// ─── commitlint.config.cjs ────────────────────────────────────────────────────

export function commitlintConfig(): string {
  return COMMITLINT_CONFIG;
}

const COMMITLINT_CONFIG = `/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert'],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
`;

// ─── Husky hooks ──────────────────────────────────────────────────────────────

export function huskyPreCommit(): string {
  return `npx lint-staged\n`;
}

export function huskyCommitMsg(): string {
  return `npx --no -- commitlint --edit $1\n`;
}

// ─── tsconfig.test.json ───────────────────────────────────────────────────────

export function tsconfigTest(): string {
  return TSCONFIG_TEST;
}

const TSCONFIG_TEST = `{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "rootDir": ".",
    "noEmit": true
  },
  "include": ["src/**/*", "tests/**/*"]
}
`;

// ─── vitest.config.ts ─────────────────────────────────────────────────────────

export function vitestConfig(excludeEntry?: string): string {
  const excludeLine = excludeEntry
    ? `          exclude: ['${excludeEntry}', 'src/**/*.d.ts'],\n`
    : `          exclude: ['src/**/*.d.ts'],\n`;

  return `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    passWithNoTests: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.ts'],
${excludeLine}    },
  },
});
`;
}
